### ISSUE TITLE
Loading transformer based models and handling phrases

### ISSUE THREAD

**Issue by iteimouri** [Pandora-Intelligence/concise-concepts#27]
Two questions: 

1. I am trying to load models that are custom build / are transformer based namely: 

```
nlp = spacy.load("en_core_web_trf")  #or spacy.load("my_custom_model") 
nlp.add_pipe("concise_concepts", config={"data": data})
doc = nlp(text)
```
running this I get: 
```
No lemmatizer found in spacy pipeline. Consider adding it for matching on LEMMA instead of exact text. 
AssertationError: Choose a spaCy model with internal embeddings, e.g. md or lg. 
```

Does this mean that concise concepts does not handle transformer based or custom spacy models? 

2. When I change the sample data to say two words or more such as: 

```
data = {
    "change": ["change my card detail", "change my address"],
    "open": ["open an account", "new account opened"],
    "close": ["close account", "terminate account", "account closure"]
}
```
I get: 
`word `change my card detail` from key `change` not present in vector model. `

Does this mean data can only handle list of words only?

**Comment by davidberenstein1957** [comment]
@iteimouri

1.a The model works based on `n_similar`-expansion and alignment for the given training data. Therefore, embeddings are needed in order to compute these similar words. You could add a [custom word2vec model](https://github.com/Pandora-Intelligence/concise-concepts/tree/main#custom-embedding-models) or a gensim pretrained one to solve this. 
1.b Lemmatization is done to max it more flexible and detect things words like `cooking`, in the same way as it would detect `cook`. If no lemmatizer is present, it just uses the exact word matches.
2 The `n_similar`-expansion is done based on the words that are present in the vocab. So, n-grams need to be included by using a custom word2vec model. 

Also, your use case looks like a sentence classification problem, so you could try using another one of my packages called `classy-classification` with `multi_label` and `include_sent` set to True.

**Comment by davidberenstein1957** [comment]
If you need any more help, feel free to ask:)
